HajoVerseny/src/HajoVerseny.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HajoVerseny.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

HajoVerseny/src/HajoVerseny.Web/Controllers/VersenyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HajoVerseny.Models;
using HajoVerseny.Web.Services;

namespace HajoVerseny.Web.Controllers
{
    public class VersenyController : Controller
    {
        public IActionResult Index()
        {
            var versenyek = new List<Verseny>
            {
                new Verseny { Nev = "Kékszalag" },
                new Verseny { Nev = "Alba Regia Kupa" },
                new Verseny { Nev = "Silwell Kupa" }
            };

            return View(versenyek);
        }


        public IActionResult Details(string nev)
        {
            var model = new Verseny
            {
                Nev = nev,
                NevezettHajok = HajoService.GetHajok()
            };

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var hajo = HajoService.GetHajo(id);

            return PartialView(hajo);
        }

        [HttpPost]
        public IActionResult Edit([FromBody]Hajo model)
        {
            return Ok();
        }
    }
}

HajoVerseny/src/HajoVerseny.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

HajoVerseny/src/HajoVerseny.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HajoVerseny/src/HajoVerseny.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699562">Add an appsetting in config and access it in app.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

HajoVerseny/src/HajoVerseny.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HajoVerseny.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HajoVerseny.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - HajoVerseny.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

HajoVerseny/src/HajoVerseny.Web/Views/Verseny/Details.cshtml
@model Verseny

<h1>@Model.Nev</h1>

<table class="table">
   <thead>
      <tr>
         <th>Név</th>
         <th>Típus</th>
         <th>Vitorlaszám</th>
         <th>Versenyzők</th>
         <th>Műveletek</th>
      </tr>
   </thead>
   <tbody>
      @foreach (Hajo hajo in Model.NevezettHajok)
      {
         <tr>
            <td>@hajo.Nev</td>
            <td>@hajo.Tipus.GetDisplayName()</td>
            <td>@hajo.VitorlaSzam</td>
            <td>@string.Join(", ", hajo.Versenyzok.Select(v => v.Nev))</td>
            <td><a class="glyphicon glyphicon-edit" onclick="initEditModal('@hajo.Id')"></a></td>
         </tr>
      }
   </tbody>
</table>

<div id="edit-modal" class="modal fade" role="dialog">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Hajó szerkesztése</h4>
         </div>
         <div class="modal-body">

         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-success" onclick="save()">Mentés</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Mégse</button>
         </div>
      </div>
   </div>
</div>

<div id="edit-versenyzo-modal" class="modal fade" role="dialog">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Versenyző szerkesztése</h4>
         </div>
         <div class="modal-body">
            @Html.Partial("EditVersenyzo", new Versenyzo())
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-success" onclick="saveVersenyzo()">Mentés</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Mégse</button>
         </div>
      </div>
   </div>
</div>

@section scripts
{
   <script>
      function initEditModal(id) {
         $.get("@Url.Action("Edit", "Verseny")/" + id, function (data) {
            $("#edit-modal .modal-body").html(data);
            $("#edit-modal").modal("show");
         })
      }

      var versenyzoToEdit = null;

      function initAddVersenyzo() {
         versenyzoToEdit = null
         $("#edit-versenyzo-modal form")[0].reset();
         $("#edit-versenyzo-modal").modal("show");
      }

      function initEditVersenyzo(versenyzo) {
         versenyzoToEdit = $(versenyzo);
         var modal = $("#edit-versenyzo-modal");
         modal.find("#Nev").val(versenyzoToEdit.data("nev"));
         modal.find("#Nem").val(versenyzoToEdit.data("nem"));
         modal.find("#SzuletesiDatum").val(versenyzoToEdit.data("szuletes"));
         modal.modal("show");
      }

      function removeVersenyzo(e) {
         e.stopPropagation();
         $(e.target).parent().remove();
      }

      function saveVersenyzo() {
         var modal = $("#edit-versenyzo-modal");
         var nev = modal.find("#Nev").val();
         var nem = modal.find("#Nem").val();
         var szuletes = modal.find("#SzuletesiDatum").val();

         var target;

         if (versenyzoToEdit != null) {
            target = versenyzoToEdit;
         } else {
            target = $("<div onclick='initEditVersenyzo(this)' class='sticker'><span class='nev'></span><a class='glyphicon glyphicon-remove' onclick='removeVersenyzo(event)'></a></div>");
         }

         target.find(".nev").text(nev);
         target.data("nev", nev);
         target.data("nem", nem);
         target.data("szuletes", szuletes);

         if (versenyzoToEdit == null) {
            $("#edit-modal .sticker-container").append(target);
         }

         modal.modal("hide");
      }

      function save() {
         var modal = $("#edit-modal");

         var versenyzok = [];
         modal.find(".sticker").each(function (i, v) {
            var versenyzo = {
               Nev: $(v).data("nev"),
               Nem: $(v).data("nem"),
               SzuletesiDatum: $(v).data("szuletes")
            }

            versenyzok.push(versenyzo);
         })

         var data = {
            Nev: modal.find("#Nev").val(),
            Tipus: modal.find("#Tipus").val(),
            VitorlaSzam: modal.find("#VitorlaSzam").val(),
            Versenyzok: versenyzok
         }

         $.ajax({
            type: "POST",
            url: "@Url.Action("Edit", "Verseny")",
            data: JSON.stringify(data),
            success: function () { modal.modal("hide"); },
            contentType: "application/json"
         });

         @*$.post("@Url.Action("Edit", "Verseny")", JSON.stringify(data), function () {
            modal.modal("hide");
         })*@
      }
   </script>
}

HajoVerseny/src/HajoVerseny.Web/Views/Verseny/Edit.cshtml
@model HajoVerseny.Models.Hajo

<form class="form-horizontal">
   <div class="form-group">
      <label class="col-sm-2 control-label">Név</label>
      <div class="col-sm-10">
         @Html.TextBoxFor(m => m.Nev, new { @class = "form-control"})
      </div>
   </div>
   <div class="form-group">
      <label class="col-sm-2 control-label">Típus</label>
      <div class="col-sm-10">
         @Html.DropDownListFor(m => m.Tipus, Html.GetEnumSelectList(typeof(HajoTipus)), new { @class = "form-control" })
      </div>
   </div>
   <div class="form-group">
      <label class="col-sm-2 control-label">Vitorlaszám</label>
      <div class="col-sm-10">
         @Html.TextBoxFor(m => m.VitorlaSzam, new { @class = "form-control" })
      </div>
   </div>
   <div class="form-group">
      <label class="col-sm-2 control-label">Versenyzők</label>
      <div class="col-sm-9 sticker-container">
         @foreach (var versenyzo in Model.Versenyzok)
         {
             <div class="sticker"
                  onclick="initEditVersenyzo(this)" 
                  data-nev="@versenyzo.Nev"
                  data-nem="@((int)versenyzo.Nem)"
                  data-szuletes="@versenyzo.SzuletesiDatum">
                <span class="nev">@versenyzo.Nev</span><a class="glyphicon glyphicon-remove" onclick="removeVersenyzo(event)"></a>
             </div>
         }
      </div>
      <div class="col-sm-1">
         <a onclick="initAddVersenyzo()" class="glyphicon glyphicon-plus"></a>
      </div>
   </div>
</form>

HajoVerseny/src/HajoVerseny.Web/Views/Verseny/EditVersenyzo.cshtml
@model HajoVerseny.Models.Versenyzo

<form class="form-horizontal">
   <div class="form-group">
      <label class="col-sm-2 control-label">Név</label>
      <div class="col-sm-10">
         @Html.TextBoxFor(m => m.Nev, new { @class = "form-control" })
      </div>
   </div>
   <div class="form-group">
      <label class="col-sm-2 control-label">Nem</label>
      <div class="col-sm-10">
         @Html.DropDownListFor(m => m.Nem, Html.GetEnumSelectList(typeof(Nem)), new { @class = "form-control" })
      </div>
   </div>
   <div class="form-group">
      <label class="col-sm-2 control-label">Születési dátum</label>
      <div class="col-sm-10">
         @Html.TextBoxFor(m => m.SzuletesiDatum, new { @class = "form-control" })
      </div>
   </div>
</form>

HajoVerseny/src/HajoVerseny.Web/Views/Verseny/Index.cshtml
@model List<HajoVerseny.Models.Verseny>

<h1>Versenyek</h1>

<table class="table">
   <thead>
      <tr>
         <th>Név</th>
         <th>Műveletek</th>
      </tr>
   </thead>
   <tbody>
      @foreach (var verseny in Model)
      {
         <tr>
            <td>@verseny.Nev</td>
            <td><a href="@Url.Action("Details", "Verseny", new { nev = verseny.Nev })" class="glyphicon glyphicon-eye-open"></a></td>
         </tr>
      }
   </tbody>
</table>